Ext.define('SmartTree.model.coltura.TableColturaSys', {
    extend: 'Ext.data.Model',
    fields: [
        {name:'n_piano', type : 'int'},
        {name:'n_coltura', type : 'int'},
        {name:'codice', type: 'string'},
        {name:'nome', type: 'string'},
        {name:'num_ufor_tot', type : 'int'},
        {name:'num_ufor_tot_p1', type : 'int'},
        {name:'num_ufor_tot_p2', type : 'int'},
        {name:'num_ufor_tot_p3', type : 'int'},
        {name:'sup_ha_tot', type : 'float'},
        {name:'sup_ha_tot_p1', type : 'float'},
        {name:'sup_ha_tot_p2', type : 'float'},
        {name:'sup_ha_tot_p3', type : 'float'},
        {name:'sic_tot_ha', type : 'float'},
        {name:'sic_tot_ha_p1', type : 'float'},
        {name:'sic_tot_ha_p2', type : 'float'},
        {name:'sic_tot_ha_p3', type : 'float'},
        {name:'za_tot_ha', type : 'float'},
        {name:'za_tot_ha_p1', type : 'float'},
        {name:'za_tot_ha_p2', type : 'float'},
        {name:'za_tot_ha_p3', type : 'float'},
        {name:'vol_inv_tot', type : 'float'},
        {name:'vol_inv_tot_p1', type : 'float'},
        {name:'vol_inv_tot_p2', type : 'float'},
        {name:'vol_inv_tot_p3', type : 'float'},
        {name:'vol_inv_med', type : 'float'},
        {name:'vol_inv_med_p1', type : 'float'},
        {name:'vol_inv_med_p2', type : 'float'},
        {name:'vol_inv_med_p3', type : 'float'},
        {name:'vol_prel_tot', type : 'float'},
        {name:'vol_prel_tot_p1', type : 'float'},
        {name:'vol_prel_tot_p2', type : 'float'},
        {name:'vol_prel_tot_p3', type : 'float'},
        {name:'vol_prel_med', type : 'float'},
        {name:'vol_prel_med_p1', type : 'float'},
        {name:'vol_prel_med_p2', type : 'float'},
        {name:'vol_prel_med_p3', type : 'float'},
        {name:'legme_v', type : 'float'},
        {name:'legme_v_p1', type : 'float'},
        {name:'legme_v_p2', type : 'float'},
        {name:'legme_v_p3', type : 'float'},
        {name:'legna_p', type : 'float'},
        {name:'legna_p_p1', type : 'float'},
        {name:'legna_p_p2', type : 'float'},
        {name:'legna_p_p3', type : 'float'},
        {name:'vol_prel_perc', type : 'float'},
        {name:'vol_prel_perc_p1', type : 'float'},
        {name:'vol_prel_perc_p2', type : 'float'},
        {name:'vol_prel_perc_p3', type : 'float'},
  ]
});
